/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Routed_breadcrumb: typeof import('./src/components/routed_breadcrumb.vue')['default']
    Routed_breadcrumb_item: typeof import('./src/components/routed_breadcrumb_item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
